/*
 * generated by Xtext 2.17.1
 */
package com.spirit.xtext.architecture.ui;

import com.google.inject.Injector;
import com.spirit.xtext.architecture.ui.internal.ArchitectureActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TgfiExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(ArchitectureActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		ArchitectureActivator activator = ArchitectureActivator.getInstance();
		return activator != null ? activator.getInjector(ArchitectureActivator.COM_SPIRIT_XTEXT_ARCHITECTURE_TGFI) : null;
	}

}
