/**
 * generated by Xtext 2.17.0
 */
package com.spirit.ihe.ui.contentassist;

import com.spirit.ihe.ui.contentassist.AbstractIHEProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class IHEProposalProvider extends AbstractIHEProposalProvider {
}
