/**
 * generated by Xtext 2.17.0
 */
package com.spirit.ihe.validation;

import com.spirit.ihe.validation.AbstractIHEValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class IHEValidator extends AbstractIHEValidator {
}
