/**
 * generated by Xtext 2.17.0
 */
package com.spirit.ihe.tests;

import com.google.inject.Inject;
import com.spirit.ihe.tests.IHEInjectorProvider;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(InjectionExtension.class)
@InjectWith(IHEInjectorProvider.class)
@SuppressWarnings("all")
public class IHEParsingTest {
  @Inject
  @Test
  public void loadModel() {
  }
}
