/*
 * generated by Xtext 2.17.0
 */
package com.spirit.ihe.ui.tests;

import com.google.inject.Injector;
import com.spirit.ihe.ui.internal.IheActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class IHEUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return IheActivator.getInstance().getInjector("com.spirit.ihe.IHE");
	}

}
