/**
 * generated by Xtext 2.12.0
 */
package com.spirit.xtext.architecture;

import com.spirit.xtext.architecture.AbstractTgfiRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class TgfiRuntimeModule extends AbstractTgfiRuntimeModule {
}
