/*
 * generated by Xtext 2.17.1
 */
package com.spirit.xtext.architecture.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import com.spirit.xtext.architecture.ide.contentassist.antlr.internal.InternalTgfiParser;
import com.spirit.xtext.architecture.services.TgfiGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class TgfiParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(TgfiGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, TgfiGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getImportAccess().getGroup(), "rule__Import__Group__0");
			builder.put(grammarAccess.getMainTgfAccess().getGroup(), "rule__MainTgf__Group__0");
			builder.put(grammarAccess.getMainTgfAccess().getGroup_3(), "rule__MainTgf__Group_3__0");
			builder.put(grammarAccess.getMainTgfAccess().getGroup_4(), "rule__MainTgf__Group_4__0");
			builder.put(grammarAccess.getMainTgfAccess().getGroup_5(), "rule__MainTgf__Group_5__0");
			builder.put(grammarAccess.getMainTgfAccess().getGroup_6(), "rule__MainTgf__Group_6__0");
			builder.put(grammarAccess.getMainTgfAccess().getGroup_7(), "rule__MainTgf__Group_7__0");
			builder.put(grammarAccess.getMainTgfAccess().getGroup_8(), "rule__MainTgf__Group_8__0");
			builder.put(grammarAccess.getMainTgfAccess().getGroup_9(), "rule__MainTgf__Group_9__0");
			builder.put(grammarAccess.getProfileAccess().getGroup(), "rule__Profile__Group__0");
			builder.put(grammarAccess.getProfileAccess().getGroup_3(), "rule__Profile__Group_3__0");
			builder.put(grammarAccess.getProfileAccess().getGroup_4(), "rule__Profile__Group_4__0");
			builder.put(grammarAccess.getProfileAccess().getGroup_5(), "rule__Profile__Group_5__0");
			builder.put(grammarAccess.getProfileAccess().getGroup_6(), "rule__Profile__Group_6__0");
			builder.put(grammarAccess.getSecRequirementsAccess().getGroup(), "rule__SecRequirements__Group__0");
			builder.put(grammarAccess.getSecRequirementsAccess().getGroup_1(), "rule__SecRequirements__Group_1__0");
			builder.put(grammarAccess.getSecRequirementsAccess().getGroup_2(), "rule__SecRequirements__Group_2__0");
			builder.put(grammarAccess.getSecRequirementsAccess().getGroup_3(), "rule__SecRequirements__Group_3__0");
			builder.put(grammarAccess.getSecRequirementsAccess().getGroup_4(), "rule__SecRequirements__Group_4__0");
			builder.put(grammarAccess.getSecRequirementsAccess().getGroup_5(), "rule__SecRequirements__Group_5__0");
			builder.put(grammarAccess.getSecRequirementsAccess().getGroup_6(), "rule__SecRequirements__Group_6__0");
			builder.put(grammarAccess.getTransactionAccess().getGroup(), "rule__Transaction__Group__0");
			builder.put(grammarAccess.getQualityAttrAccess().getGroup(), "rule__QualityAttr__Group__0");
			builder.put(grammarAccess.getRuleAccess().getGroup(), "rule__Rule__Group__0");
			builder.put(grammarAccess.getTgfiAccess().getImportElAssignment_0(), "rule__Tgfi__ImportElAssignment_0");
			builder.put(grammarAccess.getTgfiAccess().getMainAssignment_1(), "rule__Tgfi__MainAssignment_1");
			builder.put(grammarAccess.getImportAccess().getImportURIAssignment_1(), "rule__Import__ImportURIAssignment_1");
			builder.put(grammarAccess.getMainTgfAccess().getNameAssignment_1(), "rule__MainTgf__NameAssignment_1");
			builder.put(grammarAccess.getMainTgfAccess().getGenPackageAssignment_3_2(), "rule__MainTgf__GenPackageAssignment_3_2");
			builder.put(grammarAccess.getMainTgfAccess().getSatNameAssignment_4_2(), "rule__MainTgf__SatNameAssignment_4_2");
			builder.put(grammarAccess.getMainTgfAccess().getVersionNameAssignment_5_2(), "rule__MainTgf__VersionNameAssignment_5_2");
			builder.put(grammarAccess.getMainTgfAccess().getStatusNameAssignment_6_2(), "rule__MainTgf__StatusNameAssignment_6_2");
			builder.put(grammarAccess.getMainTgfAccess().getObjectiveNameAssignment_7_2(), "rule__MainTgf__ObjectiveNameAssignment_7_2");
			builder.put(grammarAccess.getMainTgfAccess().getHlfunctionNameAssignment_8_2(), "rule__MainTgf__HlfunctionNameAssignment_8_2");
			builder.put(grammarAccess.getMainTgfAccess().getRulesAssignment_9_2(), "rule__MainTgf__RulesAssignment_9_2");
			builder.put(grammarAccess.getMainTgfAccess().getProfAssignment_10(), "rule__MainTgf__ProfAssignment_10");
			builder.put(grammarAccess.getProfileAccess().getNameAssignment_1(), "rule__Profile__NameAssignment_1");
			builder.put(grammarAccess.getProfileAccess().getProfNameAssignment_3_2(), "rule__Profile__ProfNameAssignment_3_2");
			builder.put(grammarAccess.getProfileAccess().getDescrNameAssignment_4_2(), "rule__Profile__DescrNameAssignment_4_2");
			builder.put(grammarAccess.getProfileAccess().getFeatNameAssignment_5_2(), "rule__Profile__FeatNameAssignment_5_2");
			builder.put(grammarAccess.getProfileAccess().getFunctionNameAssignment_6_2(), "rule__Profile__FunctionNameAssignment_6_2");
			builder.put(grammarAccess.getProfileAccess().getActorAssignment_8(), "rule__Profile__ActorAssignment_8");
			builder.put(grammarAccess.getProfileAccess().getTransactionAssignment_10(), "rule__Profile__TransactionAssignment_10");
			builder.put(grammarAccess.getProfileAccess().getDomainAssignment_12(), "rule__Profile__DomainAssignment_12");
			builder.put(grammarAccess.getProfileAccess().getQualityattrAssignment_14(), "rule__Profile__QualityattrAssignment_14");
			builder.put(grammarAccess.getProfileAccess().getSecreAssignment_16(), "rule__Profile__SecreAssignment_16");
			builder.put(grammarAccess.getSecRequirementsAccess().getSecreGoalAssignment_1_2(), "rule__SecRequirements__SecreGoalAssignment_1_2");
			builder.put(grammarAccess.getSecRequirementsAccess().getSecreLevelAssignment_2_2(), "rule__SecRequirements__SecreLevelAssignment_2_2");
			builder.put(grammarAccess.getSecRequirementsAccess().getSecreLocationAssignment_3_2(), "rule__SecRequirements__SecreLocationAssignment_3_2");
			builder.put(grammarAccess.getSecRequirementsAccess().getSecreStateAssignment_4_2(), "rule__SecRequirements__SecreStateAssignment_4_2");
			builder.put(grammarAccess.getSecRequirementsAccess().getSecreDescrAssignment_5_2(), "rule__SecRequirements__SecreDescrAssignment_5_2");
			builder.put(grammarAccess.getSecRequirementsAccess().getSecreCategoryAssignment_6_2(), "rule__SecRequirements__SecreCategoryAssignment_6_2");
			builder.put(grammarAccess.getTgfiAccess().getUnorderedGroup(), "rule__Tgfi__UnorderedGroup");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private TgfiGrammarAccess grammarAccess;

	@Override
	protected InternalTgfiParser createParser() {
		InternalTgfiParser result = new InternalTgfiParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public TgfiGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TgfiGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
