/*
 * generated by Xtext 2.12.0
 */
package com.spirit.xtext.architecture.ide.contentassist.antlr;

import com.google.inject.Inject;
import com.spirit.xtext.architecture.ide.contentassist.antlr.internal.InternalTgfiParser;
import com.spirit.xtext.architecture.services.TgfiGrammarAccess;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class TgfiParser extends AbstractContentAssistParser {

	@Inject
	private TgfiGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalTgfiParser createParser() {
		InternalTgfiParser result = new InternalTgfiParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getImportAccess().getGroup(), "rule__Import__Group__0");
					put(grammarAccess.getMainTgfAccess().getGroup(), "rule__MainTgf__Group__0");
					put(grammarAccess.getMainTgfAccess().getGroup_3(), "rule__MainTgf__Group_3__0");
					put(grammarAccess.getMainTgfAccess().getGroup_4(), "rule__MainTgf__Group_4__0");
					put(grammarAccess.getMainTgfAccess().getGroup_5(), "rule__MainTgf__Group_5__0");
					put(grammarAccess.getMainTgfAccess().getGroup_6(), "rule__MainTgf__Group_6__0");
					put(grammarAccess.getMainTgfAccess().getGroup_7(), "rule__MainTgf__Group_7__0");
					put(grammarAccess.getMainTgfAccess().getGroup_8(), "rule__MainTgf__Group_8__0");
					put(grammarAccess.getMainTgfAccess().getGroup_9(), "rule__MainTgf__Group_9__0");
					put(grammarAccess.getProfileAccess().getGroup(), "rule__Profile__Group__0");
					put(grammarAccess.getProfileAccess().getGroup_3(), "rule__Profile__Group_3__0");
					put(grammarAccess.getProfileAccess().getGroup_4(), "rule__Profile__Group_4__0");
					put(grammarAccess.getProfileAccess().getGroup_5(), "rule__Profile__Group_5__0");
					put(grammarAccess.getProfileAccess().getGroup_6(), "rule__Profile__Group_6__0");
					put(grammarAccess.getTransactionAccess().getGroup(), "rule__Transaction__Group__0");
					put(grammarAccess.getQualityAttrAccess().getGroup(), "rule__QualityAttr__Group__0");
					put(grammarAccess.getRuleAccess().getGroup(), "rule__Rule__Group__0");
					put(grammarAccess.getTgfiAccess().getImportElAssignment_0(), "rule__Tgfi__ImportElAssignment_0");
					put(grammarAccess.getTgfiAccess().getMainAssignment_1(), "rule__Tgfi__MainAssignment_1");
					put(grammarAccess.getImportAccess().getImportURIAssignment_1(), "rule__Import__ImportURIAssignment_1");
					put(grammarAccess.getMainTgfAccess().getNameAssignment_1(), "rule__MainTgf__NameAssignment_1");
					put(grammarAccess.getMainTgfAccess().getGenPackageAssignment_3_2(), "rule__MainTgf__GenPackageAssignment_3_2");
					put(grammarAccess.getMainTgfAccess().getSatNameAssignment_4_2(), "rule__MainTgf__SatNameAssignment_4_2");
					put(grammarAccess.getMainTgfAccess().getVersionNameAssignment_5_2(), "rule__MainTgf__VersionNameAssignment_5_2");
					put(grammarAccess.getMainTgfAccess().getStatusNameAssignment_6_2(), "rule__MainTgf__StatusNameAssignment_6_2");
					put(grammarAccess.getMainTgfAccess().getObjectiveNameAssignment_7_2(), "rule__MainTgf__ObjectiveNameAssignment_7_2");
					put(grammarAccess.getMainTgfAccess().getHlfunctionNameAssignment_8_2(), "rule__MainTgf__HlfunctionNameAssignment_8_2");
					put(grammarAccess.getMainTgfAccess().getRulesAssignment_9_2(), "rule__MainTgf__RulesAssignment_9_2");
					put(grammarAccess.getMainTgfAccess().getProfAssignment_10(), "rule__MainTgf__ProfAssignment_10");
					put(grammarAccess.getProfileAccess().getNameAssignment_1(), "rule__Profile__NameAssignment_1");
					put(grammarAccess.getProfileAccess().getProfNameAssignment_3_2(), "rule__Profile__ProfNameAssignment_3_2");
					put(grammarAccess.getProfileAccess().getDescrNameAssignment_4_2(), "rule__Profile__DescrNameAssignment_4_2");
					put(grammarAccess.getProfileAccess().getFeatNameAssignment_5_2(), "rule__Profile__FeatNameAssignment_5_2");
					put(grammarAccess.getProfileAccess().getFunctionNameAssignment_6_2(), "rule__Profile__FunctionNameAssignment_6_2");
					put(grammarAccess.getProfileAccess().getActorAssignment_8(), "rule__Profile__ActorAssignment_8");
					put(grammarAccess.getProfileAccess().getTransactionAssignment_10(), "rule__Profile__TransactionAssignment_10");
					put(grammarAccess.getProfileAccess().getDomainAssignment_12(), "rule__Profile__DomainAssignment_12");
					put(grammarAccess.getProfileAccess().getQualityattrAssignment_14(), "rule__Profile__QualityattrAssignment_14");
					put(grammarAccess.getTgfiAccess().getUnorderedGroup(), "rule__Tgfi__UnorderedGroup");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public TgfiGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TgfiGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
