/**
 * generated by Xtext 2.12.0
 */
package com.spirit.xtext.architecture.validation;

import com.spirit.xtext.architecture.validation.AbstractTgfiValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class TgfiValidator extends AbstractTgfiValidator {
}
