/**
 * generated by Xtext 2.12.0
 */
package com.spirit.xtext.architecture.ide;

import com.spirit.xtext.architecture.ide.AbstractTgfiIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class TgfiIdeModule extends AbstractTgfiIdeModule {
}
