/**
 * generated by Xtext 2.17.1
 */
package com.spirit.xtext.architecture.tgfi.impl;

import com.spirit.xtext.architecture.tgfi.SecRequirements;
import com.spirit.xtext.architecture.tgfi.TgfiPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Sec Requirements</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.spirit.xtext.architecture.tgfi.impl.SecRequirementsImpl#getSecreGoal <em>Secre Goal</em>}</li>
 *   <li>{@link com.spirit.xtext.architecture.tgfi.impl.SecRequirementsImpl#getSecreLevel <em>Secre Level</em>}</li>
 *   <li>{@link com.spirit.xtext.architecture.tgfi.impl.SecRequirementsImpl#getSecreLocation <em>Secre Location</em>}</li>
 *   <li>{@link com.spirit.xtext.architecture.tgfi.impl.SecRequirementsImpl#getSecreState <em>Secre State</em>}</li>
 *   <li>{@link com.spirit.xtext.architecture.tgfi.impl.SecRequirementsImpl#getSecreDescr <em>Secre Descr</em>}</li>
 *   <li>{@link com.spirit.xtext.architecture.tgfi.impl.SecRequirementsImpl#getSecreCategory <em>Secre Category</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SecRequirementsImpl extends MinimalEObjectImpl.Container implements SecRequirements
{
  /**
   * The default value of the '{@link #getSecreGoal() <em>Secre Goal</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSecreGoal()
   * @generated
   * @ordered
   */
  protected static final String SECRE_GOAL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSecreGoal() <em>Secre Goal</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSecreGoal()
   * @generated
   * @ordered
   */
  protected String secreGoal = SECRE_GOAL_EDEFAULT;

  /**
   * The default value of the '{@link #getSecreLevel() <em>Secre Level</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSecreLevel()
   * @generated
   * @ordered
   */
  protected static final String SECRE_LEVEL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSecreLevel() <em>Secre Level</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSecreLevel()
   * @generated
   * @ordered
   */
  protected String secreLevel = SECRE_LEVEL_EDEFAULT;

  /**
   * The default value of the '{@link #getSecreLocation() <em>Secre Location</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSecreLocation()
   * @generated
   * @ordered
   */
  protected static final String SECRE_LOCATION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSecreLocation() <em>Secre Location</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSecreLocation()
   * @generated
   * @ordered
   */
  protected String secreLocation = SECRE_LOCATION_EDEFAULT;

  /**
   * The default value of the '{@link #getSecreState() <em>Secre State</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSecreState()
   * @generated
   * @ordered
   */
  protected static final String SECRE_STATE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSecreState() <em>Secre State</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSecreState()
   * @generated
   * @ordered
   */
  protected String secreState = SECRE_STATE_EDEFAULT;

  /**
   * The default value of the '{@link #getSecreDescr() <em>Secre Descr</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSecreDescr()
   * @generated
   * @ordered
   */
  protected static final String SECRE_DESCR_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSecreDescr() <em>Secre Descr</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSecreDescr()
   * @generated
   * @ordered
   */
  protected String secreDescr = SECRE_DESCR_EDEFAULT;

  /**
   * The default value of the '{@link #getSecreCategory() <em>Secre Category</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSecreCategory()
   * @generated
   * @ordered
   */
  protected static final String SECRE_CATEGORY_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSecreCategory() <em>Secre Category</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSecreCategory()
   * @generated
   * @ordered
   */
  protected String secreCategory = SECRE_CATEGORY_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SecRequirementsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TgfiPackage.Literals.SEC_REQUIREMENTS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getSecreGoal()
  {
    return secreGoal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSecreGoal(String newSecreGoal)
  {
    String oldSecreGoal = secreGoal;
    secreGoal = newSecreGoal;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TgfiPackage.SEC_REQUIREMENTS__SECRE_GOAL, oldSecreGoal, secreGoal));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getSecreLevel()
  {
    return secreLevel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSecreLevel(String newSecreLevel)
  {
    String oldSecreLevel = secreLevel;
    secreLevel = newSecreLevel;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TgfiPackage.SEC_REQUIREMENTS__SECRE_LEVEL, oldSecreLevel, secreLevel));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getSecreLocation()
  {
    return secreLocation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSecreLocation(String newSecreLocation)
  {
    String oldSecreLocation = secreLocation;
    secreLocation = newSecreLocation;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TgfiPackage.SEC_REQUIREMENTS__SECRE_LOCATION, oldSecreLocation, secreLocation));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getSecreState()
  {
    return secreState;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSecreState(String newSecreState)
  {
    String oldSecreState = secreState;
    secreState = newSecreState;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TgfiPackage.SEC_REQUIREMENTS__SECRE_STATE, oldSecreState, secreState));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getSecreDescr()
  {
    return secreDescr;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSecreDescr(String newSecreDescr)
  {
    String oldSecreDescr = secreDescr;
    secreDescr = newSecreDescr;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TgfiPackage.SEC_REQUIREMENTS__SECRE_DESCR, oldSecreDescr, secreDescr));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getSecreCategory()
  {
    return secreCategory;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSecreCategory(String newSecreCategory)
  {
    String oldSecreCategory = secreCategory;
    secreCategory = newSecreCategory;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TgfiPackage.SEC_REQUIREMENTS__SECRE_CATEGORY, oldSecreCategory, secreCategory));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TgfiPackage.SEC_REQUIREMENTS__SECRE_GOAL:
        return getSecreGoal();
      case TgfiPackage.SEC_REQUIREMENTS__SECRE_LEVEL:
        return getSecreLevel();
      case TgfiPackage.SEC_REQUIREMENTS__SECRE_LOCATION:
        return getSecreLocation();
      case TgfiPackage.SEC_REQUIREMENTS__SECRE_STATE:
        return getSecreState();
      case TgfiPackage.SEC_REQUIREMENTS__SECRE_DESCR:
        return getSecreDescr();
      case TgfiPackage.SEC_REQUIREMENTS__SECRE_CATEGORY:
        return getSecreCategory();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TgfiPackage.SEC_REQUIREMENTS__SECRE_GOAL:
        setSecreGoal((String)newValue);
        return;
      case TgfiPackage.SEC_REQUIREMENTS__SECRE_LEVEL:
        setSecreLevel((String)newValue);
        return;
      case TgfiPackage.SEC_REQUIREMENTS__SECRE_LOCATION:
        setSecreLocation((String)newValue);
        return;
      case TgfiPackage.SEC_REQUIREMENTS__SECRE_STATE:
        setSecreState((String)newValue);
        return;
      case TgfiPackage.SEC_REQUIREMENTS__SECRE_DESCR:
        setSecreDescr((String)newValue);
        return;
      case TgfiPackage.SEC_REQUIREMENTS__SECRE_CATEGORY:
        setSecreCategory((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TgfiPackage.SEC_REQUIREMENTS__SECRE_GOAL:
        setSecreGoal(SECRE_GOAL_EDEFAULT);
        return;
      case TgfiPackage.SEC_REQUIREMENTS__SECRE_LEVEL:
        setSecreLevel(SECRE_LEVEL_EDEFAULT);
        return;
      case TgfiPackage.SEC_REQUIREMENTS__SECRE_LOCATION:
        setSecreLocation(SECRE_LOCATION_EDEFAULT);
        return;
      case TgfiPackage.SEC_REQUIREMENTS__SECRE_STATE:
        setSecreState(SECRE_STATE_EDEFAULT);
        return;
      case TgfiPackage.SEC_REQUIREMENTS__SECRE_DESCR:
        setSecreDescr(SECRE_DESCR_EDEFAULT);
        return;
      case TgfiPackage.SEC_REQUIREMENTS__SECRE_CATEGORY:
        setSecreCategory(SECRE_CATEGORY_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TgfiPackage.SEC_REQUIREMENTS__SECRE_GOAL:
        return SECRE_GOAL_EDEFAULT == null ? secreGoal != null : !SECRE_GOAL_EDEFAULT.equals(secreGoal);
      case TgfiPackage.SEC_REQUIREMENTS__SECRE_LEVEL:
        return SECRE_LEVEL_EDEFAULT == null ? secreLevel != null : !SECRE_LEVEL_EDEFAULT.equals(secreLevel);
      case TgfiPackage.SEC_REQUIREMENTS__SECRE_LOCATION:
        return SECRE_LOCATION_EDEFAULT == null ? secreLocation != null : !SECRE_LOCATION_EDEFAULT.equals(secreLocation);
      case TgfiPackage.SEC_REQUIREMENTS__SECRE_STATE:
        return SECRE_STATE_EDEFAULT == null ? secreState != null : !SECRE_STATE_EDEFAULT.equals(secreState);
      case TgfiPackage.SEC_REQUIREMENTS__SECRE_DESCR:
        return SECRE_DESCR_EDEFAULT == null ? secreDescr != null : !SECRE_DESCR_EDEFAULT.equals(secreDescr);
      case TgfiPackage.SEC_REQUIREMENTS__SECRE_CATEGORY:
        return SECRE_CATEGORY_EDEFAULT == null ? secreCategory != null : !SECRE_CATEGORY_EDEFAULT.equals(secreCategory);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (secreGoal: ");
    result.append(secreGoal);
    result.append(", secreLevel: ");
    result.append(secreLevel);
    result.append(", secreLocation: ");
    result.append(secreLocation);
    result.append(", secreState: ");
    result.append(secreState);
    result.append(", secreDescr: ");
    result.append(secreDescr);
    result.append(", secreCategory: ");
    result.append(secreCategory);
    result.append(')');
    return result.toString();
  }

} //SecRequirementsImpl
