/**
 * generated by Xtext 2.17.1
 */
package com.spirit.xtext.architecture.tgfi.impl;

import com.spirit.xtext.architecture.tgfi.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class TgfiFactoryImpl extends EFactoryImpl implements TgfiFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static TgfiFactory init()
  {
    try
    {
      TgfiFactory theTgfiFactory = (TgfiFactory)EPackage.Registry.INSTANCE.getEFactory(TgfiPackage.eNS_URI);
      if (theTgfiFactory != null)
      {
        return theTgfiFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new TgfiFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TgfiFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case TgfiPackage.TGFI: return createTgfi();
      case TgfiPackage.IMPORT: return createImport();
      case TgfiPackage.MAIN_TGF: return createMainTgf();
      case TgfiPackage.PROFILE: return createProfile();
      case TgfiPackage.SEC_REQUIREMENTS: return createSecRequirements();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Tgfi createTgfi()
  {
    TgfiImpl tgfi = new TgfiImpl();
    return tgfi;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Import createImport()
  {
    ImportImpl import_ = new ImportImpl();
    return import_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MainTgf createMainTgf()
  {
    MainTgfImpl mainTgf = new MainTgfImpl();
    return mainTgf;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Profile createProfile()
  {
    ProfileImpl profile = new ProfileImpl();
    return profile;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SecRequirements createSecRequirements()
  {
    SecRequirementsImpl secRequirements = new SecRequirementsImpl();
    return secRequirements;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TgfiPackage getTgfiPackage()
  {
    return (TgfiPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static TgfiPackage getPackage()
  {
    return TgfiPackage.eINSTANCE;
  }

} //TgfiFactoryImpl
