/**
 * generated by Xtext 2.17.0
 */
package com.spirit.ihe;

import com.spirit.ihe.IHEStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class IHEStandaloneSetup extends IHEStandaloneSetupGenerated {
  public static void doSetup() {
    new IHEStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
