/**
 * generated by Xtext 2.12.0
 */
package com.spirit.xtext.architecture.tgfi;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Main Tgf</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.spirit.xtext.architecture.tgfi.MainTgf#getName <em>Name</em>}</li>
 *   <li>{@link com.spirit.xtext.architecture.tgfi.MainTgf#getGenPackage <em>Gen Package</em>}</li>
 *   <li>{@link com.spirit.xtext.architecture.tgfi.MainTgf#getSatName <em>Sat Name</em>}</li>
 *   <li>{@link com.spirit.xtext.architecture.tgfi.MainTgf#getVersionName <em>Version Name</em>}</li>
 *   <li>{@link com.spirit.xtext.architecture.tgfi.MainTgf#getStatusName <em>Status Name</em>}</li>
 *   <li>{@link com.spirit.xtext.architecture.tgfi.MainTgf#getObjectiveName <em>Objective Name</em>}</li>
 *   <li>{@link com.spirit.xtext.architecture.tgfi.MainTgf#getHlfunctionName <em>Hlfunction Name</em>}</li>
 *   <li>{@link com.spirit.xtext.architecture.tgfi.MainTgf#getRules <em>Rules</em>}</li>
 *   <li>{@link com.spirit.xtext.architecture.tgfi.MainTgf#getProf <em>Prof</em>}</li>
 * </ul>
 *
 * @see com.spirit.xtext.architecture.tgfi.TgfiPackage#getMainTgf()
 * @model
 * @generated
 */
public interface MainTgf extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.spirit.xtext.architecture.tgfi.TgfiPackage#getMainTgf_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.spirit.xtext.architecture.tgfi.MainTgf#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Gen Package</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Gen Package</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Gen Package</em>' attribute.
   * @see #setGenPackage(String)
   * @see com.spirit.xtext.architecture.tgfi.TgfiPackage#getMainTgf_GenPackage()
   * @model
   * @generated
   */
  String getGenPackage();

  /**
   * Sets the value of the '{@link com.spirit.xtext.architecture.tgfi.MainTgf#getGenPackage <em>Gen Package</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Gen Package</em>' attribute.
   * @see #getGenPackage()
   * @generated
   */
  void setGenPackage(String value);

  /**
   * Returns the value of the '<em><b>Sat Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sat Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sat Name</em>' attribute.
   * @see #setSatName(String)
   * @see com.spirit.xtext.architecture.tgfi.TgfiPackage#getMainTgf_SatName()
   * @model
   * @generated
   */
  String getSatName();

  /**
   * Sets the value of the '{@link com.spirit.xtext.architecture.tgfi.MainTgf#getSatName <em>Sat Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sat Name</em>' attribute.
   * @see #getSatName()
   * @generated
   */
  void setSatName(String value);

  /**
   * Returns the value of the '<em><b>Version Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Version Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Version Name</em>' attribute.
   * @see #setVersionName(String)
   * @see com.spirit.xtext.architecture.tgfi.TgfiPackage#getMainTgf_VersionName()
   * @model
   * @generated
   */
  String getVersionName();

  /**
   * Sets the value of the '{@link com.spirit.xtext.architecture.tgfi.MainTgf#getVersionName <em>Version Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Version Name</em>' attribute.
   * @see #getVersionName()
   * @generated
   */
  void setVersionName(String value);

  /**
   * Returns the value of the '<em><b>Status Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Status Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Status Name</em>' attribute.
   * @see #setStatusName(String)
   * @see com.spirit.xtext.architecture.tgfi.TgfiPackage#getMainTgf_StatusName()
   * @model
   * @generated
   */
  String getStatusName();

  /**
   * Sets the value of the '{@link com.spirit.xtext.architecture.tgfi.MainTgf#getStatusName <em>Status Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Status Name</em>' attribute.
   * @see #getStatusName()
   * @generated
   */
  void setStatusName(String value);

  /**
   * Returns the value of the '<em><b>Objective Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Objective Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Objective Name</em>' attribute.
   * @see #setObjectiveName(String)
   * @see com.spirit.xtext.architecture.tgfi.TgfiPackage#getMainTgf_ObjectiveName()
   * @model
   * @generated
   */
  String getObjectiveName();

  /**
   * Sets the value of the '{@link com.spirit.xtext.architecture.tgfi.MainTgf#getObjectiveName <em>Objective Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Objective Name</em>' attribute.
   * @see #getObjectiveName()
   * @generated
   */
  void setObjectiveName(String value);

  /**
   * Returns the value of the '<em><b>Hlfunction Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Hlfunction Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Hlfunction Name</em>' attribute.
   * @see #setHlfunctionName(String)
   * @see com.spirit.xtext.architecture.tgfi.TgfiPackage#getMainTgf_HlfunctionName()
   * @model
   * @generated
   */
  String getHlfunctionName();

  /**
   * Sets the value of the '{@link com.spirit.xtext.architecture.tgfi.MainTgf#getHlfunctionName <em>Hlfunction Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Hlfunction Name</em>' attribute.
   * @see #getHlfunctionName()
   * @generated
   */
  void setHlfunctionName(String value);

  /**
   * Returns the value of the '<em><b>Rules</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Rules</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rules</em>' attribute list.
   * @see com.spirit.xtext.architecture.tgfi.TgfiPackage#getMainTgf_Rules()
   * @model unique="false"
   * @generated
   */
  EList<String> getRules();

  /**
   * Returns the value of the '<em><b>Prof</b></em>' containment reference list.
   * The list contents are of type {@link com.spirit.xtext.architecture.tgfi.Profile}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Prof</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prof</em>' containment reference list.
   * @see com.spirit.xtext.architecture.tgfi.TgfiPackage#getMainTgf_Prof()
   * @model containment="true"
   * @generated
   */
  EList<Profile> getProf();

} // MainTgf
