/**
 * generated by Xtext 2.12.0
 */
package com.spirit.xtext.architecture.tgfi;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see com.spirit.xtext.architecture.tgfi.TgfiPackage
 * @generated
 */
public interface TgfiFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  TgfiFactory eINSTANCE = com.spirit.xtext.architecture.tgfi.impl.TgfiFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Tgfi</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Tgfi</em>'.
   * @generated
   */
  Tgfi createTgfi();

  /**
   * Returns a new object of class '<em>Import</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Import</em>'.
   * @generated
   */
  Import createImport();

  /**
   * Returns a new object of class '<em>Main Tgf</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Main Tgf</em>'.
   * @generated
   */
  MainTgf createMainTgf();

  /**
   * Returns a new object of class '<em>Profile</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Profile</em>'.
   * @generated
   */
  Profile createProfile();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  TgfiPackage getTgfiPackage();

} //TgfiFactory
