/*
 * generated by Xtext 2.12.0
 */
package com.spirit.xtext.architecture.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TgfiAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("com/spirit/xtext/architecture/parser/antlr/internal/InternalTgfi.tokens");
	}
}
