/*
 * generated by Xtext 2.12.0
 */
package com.spirit.xtext.architecture.parser.antlr;

import com.google.inject.Inject;
import com.spirit.xtext.architecture.parser.antlr.internal.InternalTgfiParser;
import com.spirit.xtext.architecture.services.TgfiGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class TgfiParser extends AbstractAntlrParser {

	@Inject
	private TgfiGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalTgfiParser createParser(XtextTokenStream stream) {
		return new InternalTgfiParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Tgfi";
	}

	public TgfiGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TgfiGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
