/*
 * generated by Xtext 2.17.1
 */
package com.spirit.ihe.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractIHEScopeProvider extends DelegatingScopeProvider {
}
