/*
 * generated by Xtext 2.17.1
 */
package com.spirit.ihe.ui;

import com.google.inject.Injector;
import com.spirit.ihe.ui.internal.IheActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class IHEExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(IheActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		IheActivator activator = IheActivator.getInstance();
		return activator != null ? activator.getInjector(IheActivator.COM_SPIRIT_IHE_IHE) : null;
	}

}
