/**
 * generated by Xtext 2.17.1
 */
package com.spirit.ihe.iHE;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see com.spirit.ihe.iHE.IHEPackage
 * @generated
 */
public interface IHEFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  IHEFactory eINSTANCE = com.spirit.ihe.iHE.impl.IHEFactoryImpl.init();

  /**
   * Returns a new object of class '<em>IHE</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>IHE</em>'.
   * @generated
   */
  IHE createIHE();

  /**
   * Returns a new object of class '<em>Import</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Import</em>'.
   * @generated
   */
  Import createImport();

  /**
   * Returns a new object of class '<em>Main Tgf</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Main Tgf</em>'.
   * @generated
   */
  MainTgf createMainTgf();

  /**
   * Returns a new object of class '<em>Profile</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Profile</em>'.
   * @generated
   */
  Profile createProfile();

  /**
   * Returns a new object of class '<em>Sec Requirements</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sec Requirements</em>'.
   * @generated
   */
  SecRequirements createSecRequirements();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  IHEPackage getIHEPackage();

} //IHEFactory
