/**
 * generated by Xtext 2.17.1
 */
package com.spirit.ihe.iHE;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Profile</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.spirit.ihe.iHE.Profile#getName <em>Name</em>}</li>
 *   <li>{@link com.spirit.ihe.iHE.Profile#getProfName <em>Prof Name</em>}</li>
 *   <li>{@link com.spirit.ihe.iHE.Profile#getDescrName <em>Descr Name</em>}</li>
 *   <li>{@link com.spirit.ihe.iHE.Profile#getFeatName <em>Feat Name</em>}</li>
 *   <li>{@link com.spirit.ihe.iHE.Profile#getFunctionName <em>Function Name</em>}</li>
 *   <li>{@link com.spirit.ihe.iHE.Profile#getActor <em>Actor</em>}</li>
 *   <li>{@link com.spirit.ihe.iHE.Profile#getTransaction <em>Transaction</em>}</li>
 *   <li>{@link com.spirit.ihe.iHE.Profile#getDomain <em>Domain</em>}</li>
 *   <li>{@link com.spirit.ihe.iHE.Profile#getQualityattr <em>Qualityattr</em>}</li>
 *   <li>{@link com.spirit.ihe.iHE.Profile#getSecre <em>Secre</em>}</li>
 * </ul>
 *
 * @see com.spirit.ihe.iHE.IHEPackage#getProfile()
 * @model
 * @generated
 */
public interface Profile extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.spirit.ihe.iHE.IHEPackage#getProfile_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.spirit.ihe.iHE.Profile#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Prof Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prof Name</em>' attribute.
   * @see #setProfName(String)
   * @see com.spirit.ihe.iHE.IHEPackage#getProfile_ProfName()
   * @model
   * @generated
   */
  String getProfName();

  /**
   * Sets the value of the '{@link com.spirit.ihe.iHE.Profile#getProfName <em>Prof Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Prof Name</em>' attribute.
   * @see #getProfName()
   * @generated
   */
  void setProfName(String value);

  /**
   * Returns the value of the '<em><b>Descr Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Descr Name</em>' attribute.
   * @see #setDescrName(String)
   * @see com.spirit.ihe.iHE.IHEPackage#getProfile_DescrName()
   * @model
   * @generated
   */
  String getDescrName();

  /**
   * Sets the value of the '{@link com.spirit.ihe.iHE.Profile#getDescrName <em>Descr Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Descr Name</em>' attribute.
   * @see #getDescrName()
   * @generated
   */
  void setDescrName(String value);

  /**
   * Returns the value of the '<em><b>Feat Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Feat Name</em>' attribute.
   * @see #setFeatName(String)
   * @see com.spirit.ihe.iHE.IHEPackage#getProfile_FeatName()
   * @model
   * @generated
   */
  String getFeatName();

  /**
   * Sets the value of the '{@link com.spirit.ihe.iHE.Profile#getFeatName <em>Feat Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Feat Name</em>' attribute.
   * @see #getFeatName()
   * @generated
   */
  void setFeatName(String value);

  /**
   * Returns the value of the '<em><b>Function Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Function Name</em>' attribute.
   * @see #setFunctionName(String)
   * @see com.spirit.ihe.iHE.IHEPackage#getProfile_FunctionName()
   * @model
   * @generated
   */
  String getFunctionName();

  /**
   * Sets the value of the '{@link com.spirit.ihe.iHE.Profile#getFunctionName <em>Function Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Function Name</em>' attribute.
   * @see #getFunctionName()
   * @generated
   */
  void setFunctionName(String value);

  /**
   * Returns the value of the '<em><b>Actor</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Actor</em>' attribute list.
   * @see com.spirit.ihe.iHE.IHEPackage#getProfile_Actor()
   * @model unique="false"
   * @generated
   */
  EList<String> getActor();

  /**
   * Returns the value of the '<em><b>Transaction</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Transaction</em>' attribute list.
   * @see com.spirit.ihe.iHE.IHEPackage#getProfile_Transaction()
   * @model unique="false"
   * @generated
   */
  EList<String> getTransaction();

  /**
   * Returns the value of the '<em><b>Domain</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Domain</em>' attribute list.
   * @see com.spirit.ihe.iHE.IHEPackage#getProfile_Domain()
   * @model unique="false"
   * @generated
   */
  EList<String> getDomain();

  /**
   * Returns the value of the '<em><b>Qualityattr</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Qualityattr</em>' attribute list.
   * @see com.spirit.ihe.iHE.IHEPackage#getProfile_Qualityattr()
   * @model unique="false"
   * @generated
   */
  EList<String> getQualityattr();

  /**
   * Returns the value of the '<em><b>Secre</b></em>' containment reference list.
   * The list contents are of type {@link com.spirit.ihe.iHE.SecRequirements}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Secre</em>' containment reference list.
   * @see com.spirit.ihe.iHE.IHEPackage#getProfile_Secre()
   * @model containment="true"
   * @generated
   */
  EList<SecRequirements> getSecre();

} // Profile
