/**
 * generated by Xtext 2.17.1
 */
package com.spirit.ihe.iHE;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sec Requirements</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.spirit.ihe.iHE.SecRequirements#getSecReID <em>Sec Re ID</em>}</li>
 *   <li>{@link com.spirit.ihe.iHE.SecRequirements#getSecreForm <em>Secre Form</em>}</li>
 *   <li>{@link com.spirit.ihe.iHE.SecRequirements#getSecreSensitivity <em>Secre Sensitivity</em>}</li>
 *   <li>{@link com.spirit.ihe.iHE.SecRequirements#getSecreLocation <em>Secre Location</em>}</li>
 *   <li>{@link com.spirit.ihe.iHE.SecRequirements#getSecreState <em>Secre State</em>}</li>
 *   <li>{@link com.spirit.ihe.iHE.SecRequirements#getSecreGoal <em>Secre Goal</em>}</li>
 *   <li>{@link com.spirit.ihe.iHE.SecRequirements#getSecreCountermeasure <em>Secre Countermeasure</em>}</li>
 *   <li>{@link com.spirit.ihe.iHE.SecRequirements#getSecreCategory <em>Secre Category</em>}</li>
 * </ul>
 *
 * @see com.spirit.ihe.iHE.IHEPackage#getSecRequirements()
 * @model
 * @generated
 */
public interface SecRequirements extends EObject
{
  /**
   * Returns the value of the '<em><b>Sec Re ID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sec Re ID</em>' attribute.
   * @see #setSecReID(String)
   * @see com.spirit.ihe.iHE.IHEPackage#getSecRequirements_SecReID()
   * @model
   * @generated
   */
  String getSecReID();

  /**
   * Sets the value of the '{@link com.spirit.ihe.iHE.SecRequirements#getSecReID <em>Sec Re ID</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sec Re ID</em>' attribute.
   * @see #getSecReID()
   * @generated
   */
  void setSecReID(String value);

  /**
   * Returns the value of the '<em><b>Secre Form</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Secre Form</em>' attribute.
   * @see #setSecreForm(String)
   * @see com.spirit.ihe.iHE.IHEPackage#getSecRequirements_SecreForm()
   * @model
   * @generated
   */
  String getSecreForm();

  /**
   * Sets the value of the '{@link com.spirit.ihe.iHE.SecRequirements#getSecreForm <em>Secre Form</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Secre Form</em>' attribute.
   * @see #getSecreForm()
   * @generated
   */
  void setSecreForm(String value);

  /**
   * Returns the value of the '<em><b>Secre Sensitivity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Secre Sensitivity</em>' attribute.
   * @see #setSecreSensitivity(String)
   * @see com.spirit.ihe.iHE.IHEPackage#getSecRequirements_SecreSensitivity()
   * @model
   * @generated
   */
  String getSecreSensitivity();

  /**
   * Sets the value of the '{@link com.spirit.ihe.iHE.SecRequirements#getSecreSensitivity <em>Secre Sensitivity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Secre Sensitivity</em>' attribute.
   * @see #getSecreSensitivity()
   * @generated
   */
  void setSecreSensitivity(String value);

  /**
   * Returns the value of the '<em><b>Secre Location</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Secre Location</em>' attribute.
   * @see #setSecreLocation(String)
   * @see com.spirit.ihe.iHE.IHEPackage#getSecRequirements_SecreLocation()
   * @model
   * @generated
   */
  String getSecreLocation();

  /**
   * Sets the value of the '{@link com.spirit.ihe.iHE.SecRequirements#getSecreLocation <em>Secre Location</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Secre Location</em>' attribute.
   * @see #getSecreLocation()
   * @generated
   */
  void setSecreLocation(String value);

  /**
   * Returns the value of the '<em><b>Secre State</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Secre State</em>' attribute.
   * @see #setSecreState(String)
   * @see com.spirit.ihe.iHE.IHEPackage#getSecRequirements_SecreState()
   * @model
   * @generated
   */
  String getSecreState();

  /**
   * Sets the value of the '{@link com.spirit.ihe.iHE.SecRequirements#getSecreState <em>Secre State</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Secre State</em>' attribute.
   * @see #getSecreState()
   * @generated
   */
  void setSecreState(String value);

  /**
   * Returns the value of the '<em><b>Secre Goal</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Secre Goal</em>' attribute.
   * @see #setSecreGoal(String)
   * @see com.spirit.ihe.iHE.IHEPackage#getSecRequirements_SecreGoal()
   * @model
   * @generated
   */
  String getSecreGoal();

  /**
   * Sets the value of the '{@link com.spirit.ihe.iHE.SecRequirements#getSecreGoal <em>Secre Goal</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Secre Goal</em>' attribute.
   * @see #getSecreGoal()
   * @generated
   */
  void setSecreGoal(String value);

  /**
   * Returns the value of the '<em><b>Secre Countermeasure</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Secre Countermeasure</em>' attribute.
   * @see #setSecreCountermeasure(String)
   * @see com.spirit.ihe.iHE.IHEPackage#getSecRequirements_SecreCountermeasure()
   * @model
   * @generated
   */
  String getSecreCountermeasure();

  /**
   * Sets the value of the '{@link com.spirit.ihe.iHE.SecRequirements#getSecreCountermeasure <em>Secre Countermeasure</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Secre Countermeasure</em>' attribute.
   * @see #getSecreCountermeasure()
   * @generated
   */
  void setSecreCountermeasure(String value);

  /**
   * Returns the value of the '<em><b>Secre Category</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Secre Category</em>' attribute.
   * @see #setSecreCategory(String)
   * @see com.spirit.ihe.iHE.IHEPackage#getSecRequirements_SecreCategory()
   * @model
   * @generated
   */
  String getSecreCategory();

  /**
   * Sets the value of the '{@link com.spirit.ihe.iHE.SecRequirements#getSecreCategory <em>Secre Category</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Secre Category</em>' attribute.
   * @see #getSecreCategory()
   * @generated
   */
  void setSecreCategory(String value);

} // SecRequirements
