/**
 * generated by Xtext 2.12.0
 */
package com.spirit.xtext.architecture.web;

/**
 * Initialization support for running Xtext languages in web applications.
 */
@SuppressWarnings("all")
public class TgfiWebSetup /* implements TgfiStandaloneSetup  */{
  @Override
  public /* Injector */Object createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field Guice is undefined"
      + "\nThe method or field Modules2 is undefined"
      + "\nTgfiRuntimeModule cannot be resolved."
      + "\nTgfiIdeModule cannot be resolved."
      + "\ncreateInjector cannot be resolved"
      + "\nmixin cannot be resolved");
  }
}
