/**
 * generated by Xtext 2.12.0
 */
package com.spirit.xtext.architecture.web;

import com.spirit.xtext.architecture.web.AbstractTgfiWebModule;

/**
 * Use this class to register additional components to be used within the web application.
 */
@SuppressWarnings("all")
public class TgfiWebModule extends AbstractTgfiWebModule {
}
