/*
 * generated by Xtext 2.12.0
 */
package com.spirit.xtext.architecture.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTgfiScopeProvider extends DelegatingScopeProvider {
}
