/*
 * generated by Xtext 2.12.0
 */
package com.spirit.xtext.architecture


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class TgfiRuntimeModule extends AbstractTgfiRuntimeModule {
}
