/*
 * generated by Xtext 2.12.0
 */
package com.spirit.xtext.architecture


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class TgfiStandaloneSetup extends TgfiStandaloneSetupGenerated {

	def static void doSetup() {
		new TgfiStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
