package com.spirit.togaf.bb.test;
        
import com.spirit.togaf.bb.ABB;
import com.spirit.togaf.bb.dependencies.Actor;
import com.spirit.togaf.bb.dependencies.Domain;
import com.spirit.togaf.bb.dependencies.QualityAttribute;
import com.spirit.togaf.bb.dependencies.Transaction;
        
public class DSPISR {
    private ABB dspisr;
        
    private void initP() {
        dspisr = new ABB("DSPISR", "Generated by Grouping, setter not called", "Generated by Grouping, setter on feature not called", "Generated by Grouping, setter on a function not called");
                                                
                Actor dsact = new Actor("DSAct");
                        dspisr.addActor(dsact);
                Actor dsto = new Actor("DSto");
                        dspisr.addActor(dsto);
                Actor pic = new Actor("PIC");
                        dspisr.addActor(pic);
                Actor dc = new Actor("DC");
                        dspisr.addActor(dc);
                Actor sconn = new Actor("SConn");
                        dspisr.addActor(sconn);
                Actor pis = new Actor("PIS");
                        dspisr.addActor(pis);
                
                Transaction connect = new Transaction(sconn, "Connect", sconn);
                        dspisr.addTransaction(connect);
                        
                Transaction query = new Transaction(dc, "Query", dsto);
                        dspisr.addTransaction(query);
                        
//                Transaction query = new Transaction(pic, "Query", pis);
//                        dspisr.addTransaction(query);
//                        
                Transaction feed = new Transaction(pic, "Feed", pis);
                        dspisr.addTransaction(feed);
                        
                Transaction insert = new Transaction(dsact, "Insert", dsto);
                        dspisr.addTransaction(insert);
                        
                
                Domain information = new Domain() { 
                    private String name = "Information";
                    public String getName() { return name; }
                };
                        dspisr.addDomain(information);
                Domain security = new Domain() { 
                    private String name = "Security";
                    public String getName() { return name; }
                };
                        dspisr.addDomain(security);
                Domain semantics = new Domain() { 
                    private String name = "Semantics";
                    public String getName() { return name; }
                };
                        dspisr.addDomain(semantics);
                
                QualityAttribute att0 = new QualityAttribute() {
                private String value = "sr.sw.hs_sec<1000";
                            
                @Override
                public void addRule(String value) {
                this.value = value;
                }
                            
                @Override
                public String getValue() {
                return this.value;
                }
                                        
                @Override
                public void evaluate(ABB y, ABB y2) {
                // place your implementation here
                }
                };
                        dspisr.addQualityAttribute(att0);
                QualityAttribute att1 = new QualityAttribute() {
                private String value = "sr.hw.hs_sec<3000";
                            
                @Override
                public void addRule(String value) {
                this.value = value;
                }
                            
                @Override
                public String getValue() {
                return this.value;
                }
                                        
                @Override
                public void evaluate(ABB y, ABB y2) {
                // place your implementation here
                }
                };
                        dspisr.addQualityAttribute(att1);
                QualityAttribute att2 = new QualityAttribute() {
                private String value = "pi.soundex.match_score<.83";
                            
                @Override
                public void addRule(String value) {
                this.value = value;
                }
                            
                @Override
                public String getValue() {
                return this.value;
                }
                                        
                @Override
                public void evaluate(ABB y, ABB y2) {
                // place your implementation here
                }
                };
                        dspisr.addQualityAttribute(att2);
                QualityAttribute att3 = new QualityAttribute() {
                private String value = "pi.soundex.match_sec<400";
                            
                @Override
                public void addRule(String value) {
                this.value = value;
                }
                            
                @Override
                public String getValue() {
                return this.value;
                }
                                        
                @Override
                public void evaluate(ABB y, ABB y2) {
                // place your implementation here
                }
                };
                        dspisr.addQualityAttribute(att3);
                QualityAttribute att4 = new QualityAttribute() {
                private String value = "pi.levenstein.match_sec<200";
                            
                @Override
                public void addRule(String value) {
                this.value = value;
                }
                            
                @Override
                public String getValue() {
                return this.value;
                }
                                        
                @Override
                public void evaluate(ABB y, ABB y2) {
                // place your implementation here
                }
                };
                        dspisr.addQualityAttribute(att4);
                QualityAttribute att5 = new QualityAttribute() {
                private String value = "pi.levenstein.match_score<.9";
                            
                @Override
                public void addRule(String value) {
                this.value = value;
                }
                            
                @Override
                public String getValue() {
                return this.value;
                }
                                        
                @Override
                public void evaluate(ABB y, ABB y2) {
                // place your implementation here
                }
                };
                        dspisr.addQualityAttribute(att5);
                
                
    }
    
    public DSPISR() {
            initP();
        
        }
        
        public ABB getABB() {
            return this.dspisr;
        }
}
