/*
 * generated by Xtext 2.12.0
 */
package com.spirit.xtext.architecture.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class TgfiWebModule extends AbstractTgfiWebModule {
}
