/**
 * generated by Xtext 2.17.0
 */
package com.spirit.ihe.ide;

import com.spirit.ihe.ide.AbstractIHEIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class IHEIdeModule extends AbstractIHEIdeModule {
}
