/*
 * generated by Xtext 2.17.1
 */
package com.spirit.ihe.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractIHEValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(com.spirit.ihe.iHE.IHEPackage.eINSTANCE);
		return result;
	}
}
